-- ──────────────────────────────────────────────────────────────
-- Windup 数据库初始化脚本
-- 首次启动时自动执行，创建所有表结构
-- 数据库已通过 POSTGRES_DB 环境变量自动创建
-- ──────────────────────────────────────────────────────────────

/*项目表，全局约束角色人物。*/
CREATE TABLE windup_project (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    workflow_id BIGINT,
    project_name varchar(20) NOT NULL,
    character_perspective SMALLINT NOT NULL,
    directional_movement SMALLINT NOT NULL,
    sprite_width SMALLINT NOT NULL,
    sprite_height SMALLINT NOT NULL,
    game_style TEXT,
    sprite_sample_url TEXT,
    create_at TIMESTAMPTZ,
    update_at TIMESTAMPTZ,

    CONSTRAINT uq_windup_project_user_name UNIQUE (user_id, project_name)
);

COMMENT ON TABLE windup_project IS '项目表';
COMMENT ON COLUMN windup_project.id IS '项目表主键';
COMMENT ON COLUMN windup_project.user_id IS '创建者 ID';
COMMENT ON COLUMN windup_project.workflow_id IS '工作流 ID';
COMMENT ON COLUMN windup_project.project_name IS '项目名称';
COMMENT ON COLUMN windup_project.character_perspective IS '游戏视角 ：1 = 横版视角，2 = 俯视 ，3 = 2.5D ';
COMMENT ON COLUMN windup_project.directional_movement IS '移动方向 ：1 = 单向 ，2 = 四向，3 = 八向';
COMMENT ON COLUMN windup_project.sprite_width IS '角色尺寸 宽：32 、64 、128、256、512、1024、2048';
COMMENT ON COLUMN windup_project.sprite_height IS '角色尺寸 高：32 、64 、128、256、512、1024、2048';
COMMENT ON COLUMN windup_project.game_style IS '游戏风格';
COMMENT ON COLUMN windup_project.sprite_sample_url IS '参考图URL';
COMMENT ON COLUMN windup_project.create_at IS '创建时间';
COMMENT ON COLUMN windup_project.update_at IS '修改时间';

/*用户表*/
CREATE TABLE windup_user (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(255),
    email_verified_at TIMESTAMPTZ,
    status SMALLINT DEFAULT 0,
    last_login_at TIMESTAMPTZ,
    create_at TIMESTAMPTZ,
    update_at TIMESTAMPTZ
);

COMMENT ON TABLE windup_user IS '用户表';
COMMENT ON COLUMN windup_user.id IS '用户表主键';
COMMENT ON COLUMN windup_user.email IS '邮箱地址';
COMMENT ON COLUMN windup_user.password_hash IS '用户密码（加密存储）';
COMMENT ON COLUMN windup_user.nickname IS '用户昵称';
COMMENT ON COLUMN windup_user.email_verified_at IS '邮箱校验时间';
COMMENT ON COLUMN windup_user.status IS '用户状态 默认0 正常，1 封禁';
COMMENT ON COLUMN windup_user.last_login_at IS '上次登录时间';
COMMENT ON COLUMN windup_user.create_at IS '创建时间';
COMMENT ON COLUMN windup_user.update_at IS '修改时间';

/*角色资产表*/
CREATE TABLE windup_character (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    workflow_run_id BIGINT,
    name varchar(20),
    description TEXT NULL,
    reference_image_url TEXT NULL,
    character_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    status SMALLINT NOT NULL DEFAULT 1,
    create_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_windup_character_status CHECK (status IN (0, 1)),
    CONSTRAINT ck_windup_character_data_object CHECK (jsonb_typeof(character_data) = 'object')
);

CREATE INDEX idx_windup_character_project_id
    ON windup_character (project_id);

CREATE INDEX idx_windup_character_project_update_at
    ON windup_character (project_id, update_at DESC);

COMMENT ON TABLE windup_character IS '角色资产表;角色隶属于项目,是资产库中的基本资产';
COMMENT ON COLUMN windup_character.id IS '角色资产主键';
COMMENT ON COLUMN windup_character.project_id IS '所属项目 ID';
COMMENT ON COLUMN windup_character.workflow_run_id IS '工作流执行记录表主键 ID';
COMMENT ON COLUMN windup_character.name IS '角色名称';
COMMENT ON COLUMN windup_character.description IS '角色描述';
COMMENT ON COLUMN windup_character.reference_image_url IS '角色参考图 URL;角色模板仅作为角色的参考图属性,不单独建表';
COMMENT ON COLUMN windup_character.character_data IS '角色完整数据 JSON;包含造型、动作及动作帧等信息';
COMMENT ON COLUMN windup_character.status IS '角色状态: 1-正常, 0-禁用';
COMMENT ON COLUMN windup_character.create_at IS '创建时间';
COMMENT ON COLUMN windup_character.update_at IS '最后更新时间';
COMMENT ON CONSTRAINT ck_windup_character_status ON windup_character IS '角色状态只能为 0 或 1';
COMMENT ON CONSTRAINT ck_windup_character_data_object ON windup_character IS '角色完整数据必须为 JSON 对象';

/*生成任务表*/
CREATE TABLE IF NOT EXISTS windup_generation_task (
    id            BIGSERIAL       PRIMARY KEY,
    user_id       BIGINT          NOT NULL,
    project_id    BIGINT,
    task_type     TEXT            NOT NULL DEFAULT 'character_image',
    status        TEXT            NOT NULL DEFAULT 'pending',
    input_payload JSONB           NOT NULL DEFAULT '{}',
    result_type   TEXT,
    result        JSONB,
    error_message TEXT,
    create_at     TIMESTAMPTZ     NOT NULL DEFAULT now(),
    update_at     TIMESTAMPTZ     NOT NULL DEFAULT now()
);

COMMENT ON TABLE windup_generation_task IS '生成任务表——记录每次AI生成任务';
COMMENT ON COLUMN windup_generation_task.id IS '任务主键';
COMMENT ON COLUMN windup_generation_task.user_id IS '发起用户 ID';
COMMENT ON COLUMN windup_generation_task.project_id IS '关联项目 ID';
COMMENT ON COLUMN windup_generation_task.task_type IS '任务类型：character_image = 角色图片生成';
COMMENT ON COLUMN windup_generation_task.status IS '任务状态：pending = 待执行，running = 执行中，completed = 完成，failed = 失败';
COMMENT ON COLUMN windup_generation_task.input_payload IS '任务输入参数 JSON';
COMMENT ON COLUMN windup_generation_task.result_type IS '结果类型';
COMMENT ON COLUMN windup_generation_task.result IS '任务结果 JSON';
COMMENT ON COLUMN windup_generation_task.error_message IS '错误信息（失败时记录）';
COMMENT ON COLUMN windup_generation_task.create_at IS '创建时间';
COMMENT ON COLUMN windup_generation_task.update_at IS '修改时间';

CREATE INDEX IF NOT EXISTS idx_generation_task_user_id    ON windup_generation_task (user_id);
CREATE INDEX IF NOT EXISTS idx_generation_task_project_id ON windup_generation_task (project_id);
CREATE INDEX IF NOT EXISTS idx_generation_task_status     ON windup_generation_task (status);

/*工作流执行记录表*/
CREATE TABLE windup_workflow_run (
                                     id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                     project_id        BIGINT NOT NULL,
                                     nodes             JSONB NOT NULL DEFAULT '[]',
                                     status            VARCHAR(20) NOT NULL DEFAULT 'active',
                                     version           INTEGER NOT NULL DEFAULT 1,
                                     created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

                                     CONSTRAINT fk_run_project FOREIGN KEY (project_id) REFERENCES windup_project(id)
);

COMMENT ON TABLE  windup_workflow_run IS '工作流执行记录——前端维护的节点树的持久化容器';
COMMENT ON COLUMN windup_workflow_run.id         IS '主键';
COMMENT ON COLUMN windup_workflow_run.project_id IS '关联项目 ID';
COMMENT ON COLUMN windup_workflow_run.nodes      IS '节点树 JSONB（前端自定义结构，后端不校验）';
COMMENT ON COLUMN windup_workflow_run.status     IS '状态：active=进行中，soft_deleted=已软删除';
COMMENT ON COLUMN windup_workflow_run.version    IS '版本号，从 1 递增';
COMMENT ON COLUMN windup_workflow_run.created_at IS '创建时间';

-- 索引
CREATE INDEX idx_run_project ON windup_workflow_run(project_id);


ALTER TABLE windup_character
    ADD CONSTRAINT fk_character_workflow_run
        FOREIGN KEY (workflow_run_id) REFERENCES windup_workflow_run(id);

COMMENT ON COLUMN windup_character.workflow_run_id IS '关联的工作流执行记录 ID（用于回退节点重新生成）';

CREATE INDEX idx_character_workflow_run ON windup_character(workflow_run_id) WHERE workflow_run_id IS NOT NULL;
